# Generated by Django 5.1.6 on 2025-02-26 04:22

import juegos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=juegos.models.Game.path_to_game, verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='game',
            name='image_wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to=juegos.models.Game.path_to_game, verbose_name='Wallpaper'),
        ),
    ]
