# Generated by Django 5.1.6 on 2025-02-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_game_image_thumbnail_game_image_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
